language: bash
services: docker

env:
  - BASE_TAG=9.5-alpine
  - BASE_TAG=9.6-alpine
  - BASE_TAG=10.1-alpine
  - BASE_TAG=11.1-alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - "./hooks/build.sh"

after_script:
  - docker images