#!/bin/bash

set -ex

# Only push on master branch
if [ "${SOURCE_BRANCH}" != "master" ]; then
    exit 0
fi

for tag in $(docker images jotum/postgres-healthcheck --format "{{.Tag}}");
do
    docker push "jotum/postgres-healthcheck:${tag}"
done